### ISSUE TITLE
Avoid margins in the which-key pane

### ISSUE THREAD

**Issue by idr4n** [mpwang/perfect-margin#8]
Hi,

Thanks for your package. I'm always looking for this kind of center layout setup in all my editors. This one is working great, just two things:

- Would it be possible to ignore the margins in the which-key pane or popup? I am using `(perfect-margin-visible-width 100)`, and even with 100 width, there is some which-key menus that get cutoff.
- Also, the start Doom emacs buffer keeps getting troubled by the margins, sometimes it is centered, sometimes goes completely left align. Is there anyway to avoid this behavior?

Thanks again.

**Comment by mpwang** [comment]
# which-key
At this memont you can change which-key to use minibuffer to display popup to get over this issue

```lisp
(setq which-key-popup-type 'minibuffer)
```
---
Took me sometime to look at the which-key, which-key has a variable `which-key-popup-type` to control how the popup displays. 
It seems which-key use `'side-window` by default, which use a window to display popup and is not ignored by perfect-margin, so sometimes when the menus are too long, after applying the margin to the left it get cufoff. Currently I haven't figured out how to get over this issue when using 'side-window. 

# Startup buffer sometimes is not centered
The root cause: when emacs starts, perfect-margin mode hooks actually are not triggered, because those hooks will only be triggered when window/frame change. 

One possible solution is to add hook to sth. like `change-major-mode-hook`, so when emacs starts and startup buffer change its major mode, perfect-margin hook will be triggered and the window will be rearranged.

I know the startup buffer behavior is a little bit annoying but i haven't implemented the solution and will look into it further. Thx

**Comment by idr4n** [comment]
Thanks for the reply and the suggestion to use `'minibuffer`. I will try that out.
