### ISSUE TITLE
Display buffer uses width of text as window width for deciding placement of new windows

### ISSUE THREAD

**Issue by ericsfraga** [mpwang/perfect-margin#9]
First of all, let me say that this package works very well indeed!  Just what I needed for my 38" super-wide monitor. Thank you.
The only issue I have had is that if I have a single window (placed nicely in the centre of my monitor), if a new window pops up (e.g. asking for vc-log), Emacs splits the window vertically and places the new window below my current one. This is not ideal as there is plenty of room to split horizontally but Emacs doesn't know this due to the large margins.
I have solved this with some hard-coded values: I set the perfect-margin-visible-width to slightly more than half the screen/frame width and then set split-width-threshold to 1 less than that.
I am not expecting a fix to this issue as I don't think it's necessarily fixable and so I'm simply noting it here with a potential hacky solution.
Thanks again!

**Comment by mpwang** [comment]
Glad that you enjoy this package, thanks very much for the note! 

But I've rewritten the core logic to support using side windows on left/rigth side on the same time, this version breaks previous behavior in order to simplify implementation.

Previously: setting margins for every not-ignored window
if the root window is split horizontally, there will be two windows on a super-wide monitor, the text context of each window will be center

Currently: if the main window is split, most windows will be set to have 0 margins
if the root window is split horizontally, there will be two windows on a super-wide monitor, these windows has 0 margin, the text context of each window will **NOT** be center.

Please let me know if the behavior is undesirable on a ultra-wide monitor.
